name: Test PySEIMS environments on Ubuntu

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-linux-ubuntu:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout this repository
        uses: actions/checkout@v3

      - name: Cache conda
        uses: actions/cache@v3
        env:
          # Increase this value to reset cache if etc/example-environment.yml has not changed
          CACHE_NUMBER: 0
        with:
          path: ~/conda_pkgs_dir
          key:
            ${{ runner.os }}-conda-${{ env.CACHE_NUMBER }}-${{ hashFiles('envs/py39seims_env.yml') }}
      - uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: py39seims
          environment-file: envs/py39seims_env.yml
          auto-activate-base: false
          auto-update-conda: true
          use-only-tar-bz2: true # IMPORTANT: This needs to be set for caching to work properly!

      - name: Bash
        shell: bash -el {0}
        run: |
          #conda info
          #conda list
          #printenv | sort
          cd src
          python pyseims_check.py
          